/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg260javaapp;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class AdvisorGUI extends javax.swing.JFrame {

    AdvisorController con = new AdvisorController();
    ArrayList list = new ArrayList();
    MemberRepo memRepo = new MemberRepo();
    Connection conn;
    
    public AdvisorGUI(AdvisorController control, Connection connection) {
        initComponents();
        con = control;
        conn = connection;
    }
    public void ClearFields(){
        IDField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        emailField.setText("");
        contactNumberField.setText("");
        membershipBtnGrp.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membershipBtnGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        contactNumberLabel = new javax.swing.JLabel();
        contactNumberField = new javax.swing.JTextField();
        membershipLabel = new javax.swing.JLabel();
        silverRadioButton = new javax.swing.JRadioButton();
        goldRadioButton = new javax.swing.JRadioButton();
        platinumRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        viewButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameLabel.setText("First Name:");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setText("Last Name:");

        emailLabel.setText("E-mail:");

        contactNumberLabel.setText("Contact Number:");

        membershipLabel.setText("Membership:");

        membershipBtnGrp.add(silverRadioButton);
        silverRadioButton.setText("Silver");
        silverRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silverRadioButtonActionPerformed(evt);
            }
        });

        membershipBtnGrp.add(goldRadioButton);
        goldRadioButton.setText("Gold");
        goldRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldRadioButtonActionPerformed(evt);
            }
        });

        membershipBtnGrp.add(platinumRadioButton);
        platinumRadioButton.setText("Platinum");

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        IDLabel.setText("ID:");

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IDLabel)
                                    .addComponent(contactNumberLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addComponent(lastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(membershipLabel)
                        .addGap(6, 6, 6)
                        .addComponent(silverRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goldRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platinumRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstNameField, lastNameField});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, deleteButton, exitButton, updateButton, viewButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberLabel)
                    .addComponent(contactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(membershipLabel)
                        .addComponent(silverRadioButton)
                        .addComponent(goldRadioButton)
                        .addComponent(platinumRadioButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDLabel)
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(viewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void silverRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silverRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_silverRadioButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ArrayList currentList = con.getMembers();
        String s = IDField.getText();
        int target = Integer.parseInt(s);
        boolean found = false;
        int i = 0;
        Member temp;
        while(!found){
            try{
                temp = (Member)currentList.get(i);
            }
            catch (IndexOutOfBoundsException e){
                result.setText("Member not found");
                return;
            }
            if(temp.getID() == target){
                currentList.remove(i);
                result.setText("Member ID " + target + " deleted.");
                found = true;
            }
            i++;
        }
        con.setMembers(currentList);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            if (conn!=null){
                memRepo.write(conn, con.getMembers());
                conn.close();
                System.out.println("Connection closed.");
                
                System.exit(1);
            } else {
                System.out.println("why is this null");
            }
        } catch (SQLException e){
            System.out.println("Connection Failed");
            System.out.println(e);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        String data = con.viewMembers();
        result.setText(data);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String aID, aFirstName, aLastName, aEmail, aContact;
        String error = "Please enter all details";
        if(IDField.getText().trim().isEmpty()){JOptionPane.showMessageDialog(this,error); return;}
        else{aID = IDField.getText();}
        if(firstNameField.getText().trim().isEmpty()){JOptionPane.showMessageDialog(this,error); return;}
        else{aFirstName = firstNameField.getText();}
        if(lastNameField.getText().trim().isEmpty()){JOptionPane.showMessageDialog(this,error); return;}
        else{aLastName = lastNameField.getText();}
        if(emailField.getText().trim().isEmpty()){JOptionPane.showMessageDialog(this,error); return;}
        else{aEmail = emailField.getText();}
        if(contactNumberField.getText().trim().isEmpty()){JOptionPane.showMessageDialog(this,error); return;}
        else{aContact = contactNumberField.getText();}
        String aMembership = "";
        if(silverRadioButton.isSelected()){
            aMembership = "silver";
        }
        else if(goldRadioButton.isSelected()){
            aMembership = "gold";
        }
        else if(platinumRadioButton.isSelected()){
            aMembership = "platinum";
        }
        else {
            JOptionPane.showMessageDialog(this,error);
            return;
        }
        java.util.Date today = new java.util.Date();
        long now = today.getTime();
        Date uRegDate = new Date(now);
        int id = Integer.parseInt(aID);
        
        con.register(id, aFirstName, aLastName, aEmail, aContact, aMembership, uRegDate);
        
        String data = "New member is added.";
        ClearFields();
        
        result.setText(data);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void goldRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldRadioButtonActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Member temp = new Member();
        ArrayList currentList = con.getMembers();
        String s = IDField.getText();
        int target = Integer.parseInt(s);
        int i;
        for(i = 0; i<currentList.size(); i++){
            temp = (Member)currentList.get(i);
            if(temp.getID() == target){
                currentList.remove(i);
                break;
            }
        }
        if(!firstNameField.getText().trim().isEmpty()){
            temp.setFirstName(firstNameField.getText());
        }
        if(!lastNameField.getText().trim().isEmpty()){
            temp.setLastName(lastNameField.getText());
        }
        if(!emailField.getText().trim().isEmpty()){
            temp.setEmail(emailField.getText());
        }
        if(!contactNumberField.getText().trim().isEmpty()){
            temp.setContact(contactNumberField.getText());
        }
        if(silverRadioButton.isSelected()){
            temp.setMembership("silver");
        }
        else if(goldRadioButton.isSelected()){
            temp.setMembership("gold");
        }
        else if(platinumRadioButton.isSelected()){
            temp.setMembership("platinum");
        }
        
        currentList.add(i, temp);
        con.setMembers(currentList);
        result.setText("Member updated");
        ClearFields();
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdvisorController control = new AdvisorController();
                MemberRepo repo = new MemberRepo();
                Connection connection;
                
                String connectionURL = "jdbc:derby://localhost:1527/members";
                String uName = "test";
                String uPass = "test";
                try {
                    System.out.println("Connecting to database... ");
                    connection = DriverManager.getConnection(connectionURL, uName, uPass);
                    if(connection!=null){
                        System.out.println("Connection Successful");
                        ArrayList list = repo.read(connection);
                        control.setMembers(list);
                        
                        AdvisorGUI gui = new AdvisorGUI(control, connection);
                        gui.setVisible(true);
                    }
                    else {
                        System.out.println("null");
                    }
                }
                catch (SQLException e){
                    System.out.println("Connection Failed");
                    System.out.println(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField contactNumberField;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JRadioButton goldRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.ButtonGroup membershipBtnGrp;
    private javax.swing.JLabel membershipLabel;
    private javax.swing.JRadioButton platinumRadioButton;
    private javax.swing.JTextArea result;
    private javax.swing.JRadioButton silverRadioButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
